// GUD must discover positive stories across the normal web.
// Dedicated "good news" / "positive news" publishers are intentionally excluded.
export const blockedPublisherDomains = [
    'goodnewsnetwork.org',
    'positive.news',
    'goodgoodgood.co',
    'optimistdaily.com',
    'sunnyskyz.com',
    'reasonstobecheerful.world',
    'goodnews.eu',
    'thehappynewspaper.com',
];
// The pool is intentionally much larger than the 24-story edition.
// A source can fail, publish nothing in the previous 24 hours, or simply have
// no story that passes GUD's editorial rules. The selector accepts at most one
// story per publisher domain.
const englishNewsSources = [
    // Primary / public-interest institutions
    {
        id: 'nasa',
        name: 'NASA',
        url: 'https://www.nasa.gov/feed/',
        publisherDomain: 'nasa.gov',
        category: 'science',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'esa',
        name: 'European Space Agency',
        url: 'https://www.esa.int/rssfeed/Our_Activities/Space_News',
        publisherDomain: 'esa.int',
        category: 'science',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'nsf',
        name: 'National Science Foundation',
        url: 'https://www.nsf.gov/rss/rss_www_news.xml',
        publisherDomain: 'nsf.gov',
        category: 'science',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'who',
        name: 'World Health Organization',
        url: 'https://www.who.int/rss-feeds/news-english.xml',
        publisherDomain: 'who.int',
        category: 'health',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'doe',
        name: 'U.S. Department of Energy',
        url: 'https://www.energy.gov/rss.xml',
        publisherDomain: 'energy.gov',
        category: 'technology',
        kind: 'primary',
        priority: 2,
    },
    {
        id: 'un-news',
        name: 'UN News',
        url: 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
        publisherDomain: 'news.un.org',
        category: 'society',
        kind: 'primary',
        priority: 2,
    },
    {
        id: 'smithsonian-insider',
        name: 'Smithsonian Insider',
        url: 'https://insider.si.edu/feed/',
        publisherDomain: 'si.edu',
        category: 'science',
        kind: 'primary',
        priority: 2,
    },
    // Universities / research institutions
    {
        id: 'mit',
        name: 'MIT News',
        url: 'https://news.mit.edu/rss/feed',
        publisherDomain: 'mit.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'harvard',
        name: 'Harvard Gazette',
        url: 'https://news.harvard.edu/gazette/feed',
        publisherDomain: 'harvard.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'yale',
        name: 'Yale News',
        url: 'https://news.yale.edu/news-rss',
        publisherDomain: 'yale.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'berkeley',
        name: 'Berkeley News',
        url: 'https://news.berkeley.edu/feed/',
        publisherDomain: 'berkeley.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'cornell',
        name: 'Cornell Chronicle',
        url: 'https://news.cornell.edu/taxonomy/term/15621/feed',
        publisherDomain: 'cornell.edu',
        category: 'nature',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'duke',
        name: 'Duke Today',
        url: 'https://today.duke.edu/topics/environment-%26-sustainability/rss',
        publisherDomain: 'duke.edu',
        category: 'nature',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'cambridge',
        name: 'University of Cambridge',
        url: 'https://www.cam.ac.uk/news/feed',
        publisherDomain: 'cam.ac.uk',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'eth',
        name: 'ETH Zurich',
        url: 'https://www.ethz.ch/en/news-und-veranstaltungen/eth-news/news/_jcr_content.feed.html',
        publisherDomain: 'ethz.ch',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'uw',
        name: 'University of Washington',
        url: 'https://www.washington.edu/news/feed/',
        publisherDomain: 'washington.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'michigan',
        name: 'University of Michigan Record',
        url: 'https://record.umich.edu/feed/',
        publisherDomain: 'umich.edu',
        category: 'community',
        kind: 'institution',
        priority: 1,
    },
    // Science / health / technology journalism
    {
        id: 'smithsonian',
        name: 'Smithsonian Magazine',
        url: 'https://www.smithsonianmag.com/rss/science-nature/',
        publisherDomain: 'smithsonianmag.com',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'ars-science',
        name: 'Ars Technica',
        url: 'https://feeds.arstechnica.com/arstechnica/science',
        publisherDomain: 'arstechnica.com',
        category: 'technology',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'phys-org',
        name: 'Phys.org',
        url: 'https://phys.org/rss-feed/',
        publisherDomain: 'phys.org',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'medical-xpress',
        name: 'Medical Xpress',
        url: 'https://medicalxpress.com/rss-feed/',
        publisherDomain: 'medicalxpress.com',
        category: 'health',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'science-daily',
        name: 'ScienceDaily',
        url: 'https://www.sciencedaily.com/rss/top/science.xml',
        publisherDomain: 'sciencedaily.com',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'quanta',
        name: 'Quanta Magazine',
        url: 'https://www.quantamagazine.org/feed/',
        publisherDomain: 'quantamagazine.org',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'nautilus',
        name: 'Nautilus',
        url: 'https://nautil.us/feed/',
        publisherDomain: 'nautil.us',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'undark',
        name: 'Undark',
        url: 'https://undark.org/feed/',
        publisherDomain: 'undark.org',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'aeon',
        name: 'Aeon',
        url: 'https://aeon.co/feed.rss',
        publisherDomain: 'aeon.co',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'new-atlas',
        name: 'New Atlas',
        url: 'https://newatlas.com/index.rss',
        publisherDomain: 'newatlas.com',
        category: 'technology',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'tech-xplore',
        name: 'Tech Xplore',
        url: 'https://techxplore.com/rss-feed/',
        publisherDomain: 'techxplore.com',
        category: 'technology',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'ieee-spectrum',
        name: 'IEEE Spectrum',
        url: 'https://spectrum.ieee.org/feeds/feed.rss',
        publisherDomain: 'spectrum.ieee.org',
        category: 'technology',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'live-science',
        name: 'Live Science',
        url: 'https://www.livescience.com/feeds/all',
        publisherDomain: 'livescience.com',
        category: 'science',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'popular-science',
        name: 'Popular Science',
        url: 'https://www.popsci.com/feed/',
        publisherDomain: 'popsci.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'futurity',
        name: 'Futurity',
        url: 'https://www.futurity.org/feed/',
        publisherDomain: 'futurity.org',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'the-verge',
        name: 'The Verge',
        url: 'https://www.theverge.com/rss/index.xml',
        publisherDomain: 'theverge.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'wired',
        name: 'WIRED',
        url: 'https://www.wired.com/feed/rss',
        publisherDomain: 'wired.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'techcrunch',
        name: 'TechCrunch',
        url: 'https://techcrunch.com/feed/',
        publisherDomain: 'techcrunch.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'fast-company',
        name: 'Fast Company',
        url: 'https://www.fastcompany.com/rss',
        publisherDomain: 'fastcompany.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    // Environment / climate / conservation
    {
        id: 'mongabay',
        name: 'Mongabay',
        url: 'https://news.mongabay.com/feed/',
        publisherDomain: 'mongabay.com',
        category: 'nature',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'inside-climate-news',
        name: 'Inside Climate News',
        url: 'https://insideclimatenews.org/feed/',
        publisherDomain: 'insideclimatenews.org',
        category: 'nature',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'yale-e360',
        name: 'Yale Environment 360',
        url: 'https://e360.yale.edu/feed.xml',
        publisherDomain: 'e360.yale.edu',
        category: 'nature',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'carbon-brief',
        name: 'Carbon Brief',
        url: 'https://carbonbrief.org/feed/',
        publisherDomain: 'carbonbrief.org',
        category: 'nature',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'grist',
        name: 'Grist',
        url: 'https://grist.org/feed/',
        publisherDomain: 'grist.org',
        category: 'nature',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'cleantechnica',
        name: 'CleanTechnica',
        url: 'https://cleantechnica.com/feed/',
        publisherDomain: 'cleantechnica.com',
        category: 'nature',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'electrek',
        name: 'Electrek',
        url: 'https://electrek.co/feed/',
        publisherDomain: 'electrek.co',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'canary-media',
        name: 'Canary Media',
        url: 'https://www.canarymedia.com/rss.rss',
        publisherDomain: 'canarymedia.com',
        category: 'nature',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'hakaimagazine',
        name: 'Hakai Magazine',
        url: 'https://hakaimagazine.com/feed/',
        publisherDomain: 'hakaimagazine.com',
        category: 'nature',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'earth-org',
        name: 'Earth.Org',
        url: 'https://earth.org/feed/',
        publisherDomain: 'earth.org',
        category: 'nature',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'birdlife',
        name: 'BirdLife International',
        url: 'https://www.birdlife.org/feed/',
        publisherDomain: 'birdlife.org',
        category: 'nature',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'audubon',
        name: 'Audubon',
        url: 'https://www.audubon.org/rss.xml',
        publisherDomain: 'audubon.org',
        category: 'nature',
        kind: 'institution',
        priority: 1,
    },
    {
        id: 'wildlife-society',
        name: 'The Wildlife Society',
        url: 'https://wildlife.org/feed/',
        publisherDomain: 'wildlife.org',
        category: 'nature',
        kind: 'institution',
        priority: 1,
    },
    {
        id: 'ocean-conservancy',
        name: 'Ocean Conservancy',
        url: 'https://oceanconservancy.org/feed/',
        publisherDomain: 'oceanconservancy.org',
        category: 'nature',
        kind: 'institution',
        priority: 1,
    },
    // Culture / design / architecture / archaeology
    {
        id: 'hyperallergic',
        name: 'Hyperallergic',
        url: 'https://hyperallergic.com/feed/',
        publisherDomain: 'hyperallergic.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'dezeen',
        name: 'Dezeen',
        url: 'https://www.dezeen.com/feed/',
        publisherDomain: 'dezeen.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'designboom',
        name: 'Designboom',
        url: 'https://www.designboom.com/feed/',
        publisherDomain: 'designboom.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'colossal',
        name: 'Colossal',
        url: 'https://www.thisiscolossal.com/feed/',
        publisherDomain: 'thisiscolossal.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'creative-boom',
        name: 'Creative Boom',
        url: 'https://www.creativeboom.com/feed/',
        publisherDomain: 'creativeboom.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'design-milk',
        name: 'Design Milk',
        url: 'https://design-milk.com/feed/',
        publisherDomain: 'design-milk.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'archdaily',
        name: 'ArchDaily',
        url: 'https://www.archdaily.com/feed',
        publisherDomain: 'archdaily.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'atlas-obscura',
        name: 'Atlas Obscura',
        url: 'https://www.atlasobscura.com/feeds/latest',
        publisherDomain: 'atlasobscura.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    // Society / education / mobility
    {
        id: 'edsurge',
        name: 'EdSurge',
        url: 'https://www.edsurge.com/articles_rss',
        publisherDomain: 'edsurge.com',
        category: 'education',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'streetsblog',
        name: 'Streetsblog USA',
        url: 'https://usa.streetsblog.org/feed',
        publisherDomain: 'streetsblog.org',
        category: 'society',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'nonprofit-quarterly',
        name: 'Nonprofit Quarterly',
        url: 'https://nonprofitquarterly.org/feed/',
        publisherDomain: 'nonprofitquarterly.org',
        category: 'community',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'the-conversation',
        name: 'The Conversation',
        url: 'https://theconversation.com/us/articles.atom',
        publisherDomain: 'theconversation.com',
        category: 'society',
        kind: 'journalism',
        priority: 0,
    },
    // Large general outlets / global discovery
    {
        id: 'bbc-science',
        name: 'BBC News',
        url: 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml',
        publisherDomain: 'bbc.co.uk',
        category: 'science',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'guardian-science',
        name: 'The Guardian',
        url: 'https://www.theguardian.com/science/rss',
        publisherDomain: 'theguardian.com',
        category: 'science',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'npr-science',
        name: 'NPR',
        url: 'https://feeds.npr.org/1007/rss.xml',
        publisherDomain: 'npr.org',
        category: 'science',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'dw',
        name: 'DW',
        url: 'https://rss.dw.com/xml/rss-en-all',
        publisherDomain: 'dw.com',
        category: 'society',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'france24',
        name: 'France 24',
        url: 'https://www.france24.com/en/rss',
        publisherDomain: 'france24.com',
        category: 'society',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'al-jazeera',
        name: 'Al Jazeera',
        url: 'https://www.aljazeera.com/xml/rss/all.xml',
        publisherDomain: 'aljazeera.com',
        category: 'society',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'cbc',
        name: 'CBC News',
        url: 'https://www.cbc.ca/cmlink/rss-topstories',
        publisherDomain: 'cbc.ca',
        category: 'society',
        kind: 'journalism',
        priority: 0,
    },
];

// Spanish-language sources are a separate editorial ecosystem. GUD never
// fetches both language pools and translates afterward: the requested language
// determines which publishers are contacted in the first place.
const spanishNewsSources = [
    // Science / research
    {
        id: 'sinc-ciencia',
        name: 'Agencia SINC',
        url: 'https://www.agenciasinc.es/feed/Ciencia',
        publisherDomain: 'agenciasinc.es',
        category: 'science',
        kind: 'journalism',
        priority: 3,
    },
    {
        id: 'conicet',
        name: 'CONICET',
        url: 'https://www.conicet.gov.ar/noticias-conicet/',
        publisherDomain: 'conicet.gov.ar',
        category: 'science',
        kind: 'primary',
        priority: 3,
        type: 'web',
        webPathExcludes: [
            '/novedades-conicet/',
            '/comunicacion-/',
            '/contacto/',
            '/autoridades/',
        ],
        webLinkLimit: 14,
    },
    {
        id: 'unam-global',
        name: 'UNAM Global',
        url: 'https://unamglobal.unam.mx/feed/',
        publisherDomain: 'unam.mx',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'fundacion-descubre',
        name: 'Fundación Descubre',
        url: 'https://fundaciondescubre.es/feed/',
        publisherDomain: 'fundaciondescubre.es',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    // Health
    {
        id: 'sinc-salud',
        name: 'Agencia SINC',
        url: 'https://www.agenciasinc.es/feed/Salud',
        publisherDomain: 'agenciasinc.es',
        category: 'health',
        kind: 'journalism',
        priority: 3,
    },
    {
        id: 'clarin-buena-vida',
        name: 'Clarín',
        url: 'https://www.clarin.com/rss/buena-vida/',
        publisherDomain: 'clarin.com',
        category: 'health',
        kind: 'journalism',
        priority: 0,
    },
    // Nature / environment
    {
        id: 'sinc-tierra',
        name: 'Agencia SINC',
        url: 'https://www.agenciasinc.es/feed/Tierra',
        publisherDomain: 'agenciasinc.es',
        category: 'nature',
        kind: 'journalism',
        priority: 3,
    },
    {
        id: 'mongabay-latam',
        name: 'Mongabay Latam',
        url: 'https://es.mongabay.com/feed/',
        publisherDomain: 'mongabay.com',
        category: 'nature',
        kind: 'journalism',
        priority: 2,
    },
    {
        id: 'efeverde',
        name: 'EFEverde',
        url: 'https://efeverde.com/feed/',
        publisherDomain: 'efeverde.com',
        category: 'nature',
        kind: 'journalism',
        priority: 2,
    },
    // Technology
    {
        id: 'sinc-tecnologia',
        name: 'Agencia SINC',
        url: 'https://www.agenciasinc.es/feed/Tecnologia',
        publisherDomain: 'agenciasinc.es',
        category: 'technology',
        kind: 'journalism',
        priority: 2,
    },
    {
        id: 'xataka',
        name: 'Xataka',
        url: 'https://www.xataka.com/index.xml',
        publisherDomain: 'xataka.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'genbeta',
        name: 'Genbeta',
        url: 'https://www.genbeta.com/index.xml',
        publisherDomain: 'genbeta.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    // Society / public interest
    {
        id: 'sinc-sociedad',
        name: 'Agencia SINC',
        url: 'https://www.agenciasinc.es/feed/Sociedad',
        publisherDomain: 'agenciasinc.es',
        category: 'society',
        kind: 'journalism',
        priority: 2,
    },
    {
        id: 'clarin-sociedad',
        name: 'Clarín',
        url: 'https://www.clarin.com/rss/sociedad/',
        publisherDomain: 'clarin.com',
        category: 'society',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'bbc-mundo',
        name: 'BBC Mundo',
        url: 'https://feeds.bbci.co.uk/mundo/rss.xml',
        publisherDomain: 'bbc.co.uk',
        category: 'society',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'dw-es',
        name: 'DW Español',
        url: 'https://rss.dw.com/xml/rss-sp-all',
        publisherDomain: 'dw.com',
        category: 'society',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'france24-es',
        name: 'France 24 Español',
        url: 'https://www.france24.com/es/rss',
        publisherDomain: 'france24.com',
        category: 'society',
        kind: 'journalism',
        priority: 0,
    },
    // Education
    {
        id: 'educacion-3-0',
        name: 'Educación 3.0',
        url: 'https://www.educaciontrespuntocero.com/feed/',
        publisherDomain: 'educaciontrespuntocero.com',
        category: 'education',
        kind: 'journalism',
        priority: 1,
    },
    // Culture
    {
        id: 'clarin-cultura',
        name: 'Clarín',
        url: 'https://www.clarin.com/rss/cultura/',
        publisherDomain: 'clarin.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'cultura-inquieta',
        name: 'Cultura Inquieta',
        url: 'https://culturainquieta.com/feed/',
        publisherDomain: 'culturainquieta.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    // Community / constructive local stories
    {
        id: 'the-conversation-es',
        name: 'The Conversation España',
        url: 'https://theconversation.com/es/articles.atom',
        publisherDomain: 'theconversation.com',
        category: 'community',
        kind: 'journalism',
        priority: 1,
    },
    // Additional high-signal Hispanoamerican science / culture / design sources.
    // These expand discovery only. The v6.3 editorial eligibility classifier is
    // intentionally unchanged, so source quality never bypasses GUD's outcome gate.
    {
        id: 'agencia-ctys',
        name: 'Agencia CTyS',
        url: 'https://www.ctys.com.ar/feed/',
        publisherDomain: 'ctys.com.ar',
        category: 'science',
        kind: 'institution',
        priority: 3,
    },
    {
        id: 'pesquisa-javeriana',
        name: 'Pesquisa Javeriana',
        url: 'https://www.javeriana.edu.co/pesquisa/feed/',
        publisherDomain: 'javeriana.edu.co',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'revista-anfibia',
        name: 'Revista Anfibia',
        url: 'https://www.revistaanfibia.com/feed/',
        publisherDomain: 'revistaanfibia.com',
        category: 'culture',
        kind: 'journalism',
        priority: 2,
    },
    {
        id: 'archdaily-es',
        name: 'ArchDaily en Español',
        url: 'https://www.archdaily.cl/cl/feed',
        publisherDomain: 'archdaily.cl',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'revista-digital-unam',
        name: 'Revista Digital Universitaria UNAM',
        url: 'https://www.revista.unam.mx/feed/',
        publisherDomain: 'revista.unam.mx',
        category: 'education',
        kind: 'institution',
        priority: 1,
    },
    {
        id: 'efesalud',
        name: 'EFE Salud',
        url: 'https://efesalud.com/feed/',
        publisherDomain: 'efesalud.com',
        category: 'health',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'dialogue-earth-es',
        name: 'Dialogue Earth',
        url: 'https://dialogue.earth/es/feed/',
        publisherDomain: 'dialogue.earth',
        category: 'nature',
        kind: 'journalism',
        priority: 1,
    },

    // v6.5 — GUD Source Network: Argentina-heavy culture, photography,
    // nature, universities and independent magazines. These sources only expand
    // discovery. Every item still passes the unchanged v6.3 eligibility gate,
    // hard rejects, scoring, semantic dedupe and one-story-per-publisher rule.

    // Argentina — science / universities / public knowledge
    {
        id: 'fundacion-miguel-lillo',
        name: 'Fundación Miguel Lillo',
        url: 'https://lillo.org.ar/prensa',
        publisherDomain: 'lillo.org.ar',
        category: 'nature',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/node/'],
        webPathExcludes: ['/node/1256', '/node/3205'],
        webLinkLimit: 18,
    },
    {
        id: 'exactas-uba',
        name: 'Exactas UBA',
        url: 'https://exactas.uba.ar/feed/',
        publisherDomain: 'uba.ar',
        category: 'science',
        kind: 'institution',
        priority: 3,
    },
    {
        id: 'universidad-nacional-quilmes',
        name: 'Universidad Nacional de Quilmes',
        url: 'https://www.unq.edu.ar/feed/',
        publisherDomain: 'unq.edu.ar',
        category: 'education',
        kind: 'institution',
        priority: 2,
    },

    // Argentina — regional nature / culture
    {
        id: 'diario-andino-verde',
        name: 'Diario Andino · Agenda Verde',
        url: 'https://www.diarioandino.com.ar/rss/agenda-verde/',
        publisherDomain: 'diarioandino.com.ar',
        category: 'nature',
        kind: 'journalism',
        priority: 2,
    },
    {
        id: 'diario-andino-cultura',
        name: 'Diario Andino · Arte/Cultura',
        url: 'https://www.diarioandino.com.ar/rss/arte-cultura/',
        publisherDomain: 'diarioandino.com.ar',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'pagina12-ciencia',
        name: 'Página/12 Ciencia',
        url: 'https://www.pagina12.com.ar/arc/outboundfeeds/rss/secciones/ciencia/notas',
        publisherDomain: 'pagina12.com.ar',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'pagina12-universidad',
        name: 'Página/12 Universidad',
        url: 'https://www.pagina12.com.ar/arc/outboundfeeds/rss/secciones/universidad/notas',
        publisherDomain: 'pagina12.com.ar',
        category: 'education',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'pagina12-cultura',
        name: 'Página/12 Cultura',
        url: 'https://www.pagina12.com.ar/arc/outboundfeeds/rss/secciones/cultura/notas',
        publisherDomain: 'pagina12.com.ar',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'rosario3',
        name: 'Rosario3',
        url: 'https://www.rosario3.com/rss.html',
        publisherDomain: 'rosario3.com',
        category: 'society',
        kind: 'journalism',
        priority: 1,
    },

    // Argentina — independent culture / photography newsletters
    {
        id: 'leedor-substack',
        name: 'Leedor',
        url: 'https://sitioleedor.substack.com/feed',
        publisherDomain: 'sitioleedor.substack.com',
        category: 'culture',
        kind: 'journalism',
        priority: 2,
    },
    {
        id: 'la-marea-substack',
        name: 'La marea',
        url: 'https://lamarea.substack.com/feed',
        publisherDomain: 'lamarea.substack.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'la-otra-historia-del-arte',
        name: 'La Otra Historia del Arte',
        url: 'https://laotrahistoriadelarte.substack.com/feed',
        publisherDomain: 'laotrahistoriadelarte.substack.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },

    // Spanish-language culture / photography / nature magazines
    {
        id: 'fauna-patagonia-substack',
        name: 'Fauna Patagonia',
        url: 'https://faunapatagonia.substack.com/feed',
        publisherDomain: 'faunapatagonia.substack.com',
        category: 'nature',
        kind: 'journalism',
        priority: 2,
    },
    {
        id: 'la-camarada-substack',
        name: 'La Camarada',
        url: 'https://lacamarada.substack.com/feed',
        publisherDomain: 'lacamarada.substack.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'artishock-revista',
        name: 'Artishock Revista',
        url: 'https://artishockrevista.com/',
        publisherDomain: 'artishockrevista.com',
        category: 'culture',
        kind: 'journalism',
        priority: 2,
        type: 'web',
        webPathExcludes: ['/categoria/', '/tag/', '/author/', '/contacto/'],
        webLinkLimit: 12,
    },
    {
        id: 'revista-otra-parte',
        name: 'Otra Parte',
        url: 'https://www.revistaotraparte.com/feed/',
        publisherDomain: 'revistaotraparte.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'letras-libres',
        name: 'Letras Libres',
        url: 'https://letraslibres.com/feed/',
        publisherDomain: 'letraslibres.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'photolari',
        name: 'Photolari',
        url: 'https://photolari.com/feed/',
        publisherDomain: 'photolari.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'muy-interesante',
        name: 'Muy Interesante',
        url: 'https://www.muyinteresante.com/feed/',
        publisherDomain: 'muyinteresante.com',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'jot-down',
        name: 'Jot Down',
        url: 'https://www.jotdown.es/feed/',
        publisherDomain: 'jotdown.es',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },


    // v6.6 — public web adapters for high-signal Hispanoamerican sources whose
    // RSS is absent, incomplete or unreliable. The adapter reads only public
    // listing/article metadata. Every item then goes through the exact same
    // v6.3 editorial eligibility gate, hard rejects, score and dedupe.

    // Argentina — science and conservation
    {
        id: 'argentina-investiga-web',
        name: 'Argentina Investiga',
        url: 'https://argentinainvestiga.edu.ar/',
        publisherDomain: 'argentinainvestiga.edu.ar',
        category: 'science',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/noticia.php'],
        webLinkLimit: 24,
    },
    {
        id: 'leloir-web',
        name: 'Fundación Instituto Leloir',
        url: 'https://www.leloir.org.ar/',
        publisherDomain: 'leloir.org.ar',
        category: 'science',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathExcludes: [
            '/comunicacion-de-la-ciencia',
            '/el-instituto',
            '/contacto',
            '/donar',
            '/laboratorios',
        ],
        webLinkLimit: 20,
    },
    {
        id: 'aves-argentinas-web',
        name: 'Aves Argentinas',
        url: 'https://www.avesargentinas.org.ar/noticias',
        publisherDomain: 'avesargentinas.org.ar',
        category: 'nature',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/noticia/'],
        webLinkLimit: 20,
    },
    {
        id: 'rewilding-argentina-web',
        name: 'Rewilding Argentina',
        url: 'https://rewildingargentina.org/stories',
        publisherDomain: 'rewildingargentina.org',
        category: 'nature',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/stories/'],
        webLinkLimit: 20,
    },

    // Chile — research, biodiversity and restoration
    {
        id: 'uc-chile-investigacion-web',
        name: 'Pontificia Universidad Católica de Chile · Investigación',
        url: 'https://investigacion.uc.cl/noticias/',
        publisherDomain: 'uc.cl',
        category: 'science',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/noticias/'],
        webLinkLimit: 20,
    },
    {
        id: 'uchile-investigacion-web',
        name: 'Universidad de Chile · Investigación',
        url: 'https://uchile.cl/investigacion',
        publisherDomain: 'uchile.cl',
        category: 'science',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/noticias/'],
        webLinkLimit: 22,
    },
    {
        id: 'rewilding-chile-web',
        name: 'Rewilding Chile',
        url: 'https://www.rewildingchile.org/news/',
        publisherDomain: 'rewildingchile.org',
        category: 'nature',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/news/'],
        webLinkLimit: 20,
    },

    // Colombia
    {
        id: 'agencia-unal-web',
        name: 'Agencia UNAL',
        url: 'https://agenciadenoticias.unal.edu.co/',
        publisherDomain: 'unal.edu.co',
        category: 'science',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/detalle/'],
        webLinkLimit: 24,
    },

    // México
    {
        id: 'tecscience-web',
        name: 'TecScience',
        url: 'https://tecscience.tec.mx/es/',
        publisherDomain: 'tecscience.tec.mx',
        category: 'science',
        kind: 'journalism',
        priority: 3,
        type: 'web',
        webPathIncludes: [
            '/es/salud/',
            '/es/transformacion-industrial/',
            '/es/educacion-y-humanismo/',
            '/es/ciudades-y-comunidades-prosperas/',
            '/es/humano-social/',
        ],
        webLinkLimit: 24,
    },
    {
        id: 'ciencia-unam-web',
        name: 'Ciencia UNAM',
        url: 'https://ciencia.unam.mx/',
        publisherDomain: 'ciencia.unam.mx',
        category: 'science',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/leer/'],
        webLinkLimit: 22,
    },

    // Perú
    {
        id: 'puntoedu-pucp-web',
        name: 'PuntoEdu PUCP · Investigaciones',
        url: 'https://puntoedu.pucp.edu.pe/investigaciones/',
        publisherDomain: 'puntoedu.pucp.edu.pe',
        category: 'science',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/investigaciones/'],
        webPathExcludes: ['/investigaciones/investigacion/'],
        webLinkLimit: 22,
    },

    // Costa Rica / Central America
    {
        id: 'ucr-ciencia-web',
        name: 'Universidad de Costa Rica · Ciencia y Tecnología',
        url: 'https://www.ucr.ac.cr/noticias/categorias/ciencia-y-tecnologia/',
        publisherDomain: 'ucr.ac.cr',
        category: 'science',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/noticias/2026/'],
        webLinkLimit: 24,
    },

    // Panamá / regional tropical science
    {
        id: 'smithsonian-tropical-es-web',
        name: 'Smithsonian Tropical Research Institute · Español',
        url: 'https://stri.si.edu/es/disciplinas/biodiversidad',
        publisherDomain: 'stri.si.edu',
        category: 'nature',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathIncludes: ['/es/'],
        webPathExcludes: [
            '/es/disciplinas/',
            '/es/programas-academicos/',
            '/es/persona/',
        ],
        webLinkLimit: 18,
    },


    // v6.6 — regional depth beyond Argentina. These public web adapters favor
    // university research, science communication and concrete institutional
    // outcomes across Hispanoamérica. The editorial classifier remains unchanged.

    // Paraguay
    {
        id: 'una-paraguay-investigacion-web',
        name: 'Universidad Nacional de Asunción · Investigación',
        url: 'https://www.una.py/investigacion',
        publisherDomain: 'una.py',
        category: 'science',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathExcludes: ['/tag/', '/category/', '/author/', '/contacto/'],
        webLinkLimit: 14,
    },

    // Ecuador
    {
        id: 'ucuenca-ciencia-web',
        name: 'Universidad de Cuenca · Ciencia',
        url: 'https://www.ucuenca.edu.ec/investigacion-innovacion/comunicacion-de-la-ciencia/',
        publisherDomain: 'ucuenca.edu.ec',
        category: 'science',
        kind: 'institution',
        priority: 3,
        type: 'web',
        webPathExcludes: ['/evento/', '/events/', '/contacto/'],
        webLinkLimit: 14,
    },

    // Uruguay
    {
        id: 'udelar-noticias-web',
        name: 'Universidad de la República',
        url: 'https://udelar.edu.uy/noticias',
        publisherDomain: 'udelar.edu.uy',
        category: 'education',
        kind: 'institution',
        priority: 2,
        type: 'web',
        webPathExcludes: ['/agenda/', '/institucional/', '/contacto/'],
        webLinkLimit: 14,
    },

    // Architecture / design / photography. These belong to the normal NEWS
    // pipeline only when they describe a realized outcome. Future exhibitions,
    // calendars and cultural listings belong to GUD Agenda instead.
    {
        id: 'arquine-web',
        name: 'Arquine',
        url: 'https://arquine.com/categoria/noticias/',
        publisherDomain: 'arquine.com',
        category: 'culture',
        kind: 'journalism',
        priority: 2,
        type: 'web',
        webPathExcludes: [
            '/categoria/',
            '/revista/',
            '/libros/',
            '/tienda/',
            '/newsletter/',
            '/suscripcion/',
            '/acerca-de-arquine/',
        ],
        webLinkLimit: 14,
    },
    {
        id: 'arqa-latam-web',
        name: 'ARQA',
        url: 'https://arqa.com/',
        publisherDomain: 'arqa.com',
        category: 'culture',
        kind: 'journalism',
        priority: 2,
        type: 'web',
        webPathExcludes: [
            '/suscripciones',
            '/empresas/',
            '/arqa',
            '/publicidad',
            '/contacto',
        ],
        webLinkLimit: 14,
    },
    {
        id: 'axxis-colombia-web',
        name: 'Revista AXXIS',
        url: 'https://revistaaxxis.com.co/',
        publisherDomain: 'revistaaxxis.com.co',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
        type: 'web',
        webPathExcludes: [
            '/suscripciones/',
            '/sobre-nosotros/',
            '/terminos',
            '/politicas',
        ],
        webLinkLimit: 14,
    },
    {
        id: 'metalocus-arquitectura-web',
        name: 'METALOCUS',
        url: 'https://www.metalocus.es/es/category/arquitectura',
        publisherDomain: 'metalocus.es',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
        type: 'web',
        webPathExcludes: ['/es/category/', '/es/search/', '/es/user/'],
        webLinkLimit: 12,
    },
    {
        id: 'clavoardiendo-web',
        name: 'Clavoardiendo Magazine',
        url: 'https://clavoardiendo-magazine.com/',
        publisherDomain: 'clavoardiendo-magazine.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
        type: 'web',
        webPathExcludes: [
            '/quienes-somos/',
            '/contacto/',
            '/hazte-socio',
            '/author/',
            '/tag/',
        ],
        webLinkLimit: 12,
    },

    // EL PAÍS publishes official RSS feeds. These widen the Spanish-language
    // discovery pool; publisher-domain uniqueness still allows at most one
    // EL PAÍS story into a daily edition.
    {
        id: 'elpais-america',
        name: 'EL PAÍS América',
        url: 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/america/portada',
        publisherDomain: 'elpais.com',
        category: 'society',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'elpais-ciencia',
        name: 'EL PAÍS Ciencia',
        url: 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ciencia/portada',
        publisherDomain: 'elpais.com',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'elpais-clima',
        name: 'EL PAÍS Clima y Medio Ambiente',
        url: 'https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/section/clima-y-medio-ambiente',
        publisherDomain: 'elpais.com',
        category: 'nature',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'elpais-educacion',
        name: 'EL PAÍS Educación',
        url: 'https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/section/educacion',
        publisherDomain: 'elpais.com',
        category: 'education',
        kind: 'journalism',
        priority: 1,
    },
];

export const getNewsSources = (edition = 'english') =>
    edition === 'latam' || edition === 'es'
        ? spanishNewsSources
        : englishNewsSources;

// Backward-compatible export for any tooling that still imports newsSources.
export const newsSources = englishNewsSources;
