#!/usr/bin/env python3
"""Create reproducible synthetic editorial bootstrap fixtures (not validated real news)."""
import json
from pathlib import Path
positive = [
 'Scientists restore a damaged wetland after years of conservation work',
 'Local clinics expand free health care access for underserved families',
 'A new treatment reduced infection rates in a completed clinical trial',
 'Researchers develop a tool that improves accessibility for blind people',
 'A library reopens after community volunteers rebuild the building',
 'Wildlife populations recovered following habitat restoration',
 'A city reports sustained reductions in particulate air pollution',
 'A vaccination campaign prevented thousands of infections',
 'Affordable housing units open to formerly homeless residents',
 'Solar capacity grows while coal emissions fall in annual statistics',
 'An endangered species returns to a protected national park',
 'A museum digitizes rare archives and opens free public access',
 'New water purification technology removes toxic contaminants in field tests',
 'Schools improve literacy rates following a funded reading initiative',
 'A community garden provides fresh vegetables to local families',
 'Scientists document a new previously unknown species in the rainforest',
 'Free public transport launches for people with disabilities',
 'Volunteers successfully reconnect isolated communities after bridge restoration',
 'Researchers demonstrate an efficient method of cleaning polluted rivers',
 'An international agreement leads to verified landmine removal in villages',
 'Ceasefire enables families to return home and humanitarian aid to arrive',
 'Farmers report higher harvests with measurably reduced water consumption',
 'Researchers discover a previously unknown beneficial soil organism',
 'A hospital successfully reduces waiting times for emergency patients',
 'An education program awards scholarships to low-income students',
 'Scientists identify an enzyme that removes pollution from drinking water',
 'Bird nesting sites recover following restoration of coastal habitat',
 'A historic theatre is restored and reopens to the public',
 'A town provides reliable electricity to previously disconnected households',
 'A study demonstrates safer recovery outcomes for stroke patients',
 'Científicos restauran un humedal dañado tras años de conservación',
 'Hospitales amplían el acceso gratuito a tratamientos para familias vulnerables',
 'Un ensayo clínico confirma que el tratamiento reduce infecciones',
 'Investigadores desarrollan una herramienta que mejora la accesibilidad',
 'La biblioteca del barrio reabre después de la reconstrucción comunitaria',
 'La biodiversidad se recuperó gracias a la restauración del hábitat',
 'Una ciudad reduce de forma sostenida sus emisiones contaminantes',
 'Una campaña de vacunación evita miles de infecciones',
 'Abren viviendas sociales para personas que estaban en situación de calle',
 'Aumenta la energía solar mientras disminuyen las emisiones de carbón',
 'Una especie en peligro regresa al parque nacional protegido',
 'El museo digitaliza su archivo y abre el acceso gratuito al público',
 'Una nueva técnica elimina contaminantes del agua en pruebas verificadas',
 'Mejoran las tasas de alfabetización tras una iniciativa escolar',
 'Un huerto comunitario proporciona alimentos frescos a familias',
 'Científicos descubren una nueva especie en la selva tropical',
 'Se inaugura transporte público accesible y gratuito para personas con discapacidad',
 'Voluntarios reconstruyen un puente y reconectan comunidades aisladas',
 'Investigadores demuestran un método eficaz para limpiar ríos contaminados',
 'El alto el fuego permite el regreso de familias y la entrega de ayuda humanitaria',
 'Agricultores producen más alimentos utilizando menos agua',
 'Investigadores descubren un microorganismo beneficioso en el suelo',
 'Un hospital reduce los tiempos de espera en urgencias',
 'Un programa de educación otorga becas a estudiantes de bajos ingresos',
 'Restauran un teatro histórico y vuelve a abrir sus puertas al público',
]
negative = [
 'Ukraine celebrates successful military offensive against rival forces',
 'Military forces restored control of strategic positions after battle',
 'New combat drones give army an advantage on the frontline',
 'A football team defeats rivals and wins the championship',
 'A company beats competitors with record quarterly profits',
 'Climate change threatens coral reef recovery in warming oceans',
 'Scientists discover an alarming decline in rainforest biodiversity',
 'Restored reefs face record losses as warming intensifies',
 'Global emissions rise to another record high despite commitments',
 'Researchers find that the disease spreads faster than previously thought',
 'A promising new medicine could one day prevent disease',
 'Government announces plans to restore a damaged hospital next year',
 'A clinical test in mice might improve future cancer treatments',
 'A new study links a popular diet to better health without causal evidence',
 'Flood victims rescued as the disaster leaves dozens dead',
 'Military engineers successfully launch a new missile system',
 'Sports star wins the award for best player of the year',
 'Scientists record accelerating glacier melt in mountain regions',
 'Officials order urgent measures after pollution reaches dangerous levels',
 'A prototype may someday reduce emissions if investors fund development',
 'Major tech brand launches its most expensive smartphone yet',
 'Experts warn endangered species is losing its chance to recover',
 'A celebrity looks back on an impressive personal career',
 'A corporation announces its ambition to improve global sustainability',
 'Researchers discover that oceans are warming even faster',
 'The army retakes a village during the ongoing conflict',
 'A government claims victory in a territorial dispute',
 'A football club restores its place at the top of the league',
 'Record-breaking heat threatens the ability of forests to recover',
 'Scientists find rising mortality among coastal animals',
 'Ucrania celebra una victoria militar tras recuperar posiciones estratégicas',
 'Las fuerzas armadas anuncian el éxito de una nueva ofensiva',
 'Un sistema de drones de combate obtiene ventaja sobre el enemigo',
 'Argentina vence a Brasil y gana la final del campeonato',
 'Una empresa supera a sus competidores con ganancias récord',
 'El cambio climático amenaza la recuperación de los arrecifes',
 'Investigadores descubren un alarmante descenso de la biodiversidad',
 'Arrecifes restaurados sufren pérdidas récord por el calentamiento',
 'Las emisiones globales vuelven a marcar máximos históricos',
 'Científicos hallan que la enfermedad se propaga más rápido de lo previsto',
 'Una medicina prometedora podría prevenir enfermedades en el futuro',
 'El gobierno anuncia un plan para reconstruir un hospital el próximo año',
 'Pruebas en ratones podrían mejorar futuros tratamientos',
 'Un estudio asocia un alimento con una mejor salud sin demostrar causalidad',
 'Rescatan a sobrevivientes de una inundación que deja decenas de muertos',
 'Ingenieros militares prueban un nuevo sistema de misiles con éxito',
 'Un futbolista gana el premio al mejor jugador del año',
 'Científicos documentan un deshielo acelerado de los glaciares',
 'Las autoridades ordenan medidas urgentes tras un desastre ambiental',
 'Un prototipo podría reducir emisiones si consigue financiación',
 'Una marca presenta su teléfono más caro hasta la fecha',
 'Expertos alertan de que la especie tiene menos posibilidades de recuperarse',
 'Una celebridad recuerda su exitosa trayectoria personal',
 'Una empresa promete mejorar la sostenibilidad mundial',
 'Científicos descubren que los océanos se calientan todavía más rápido',
 'El ejército retoma un pueblo en medio del conflicto armado',
 'Un gobierno declara su victoria en una disputa territorial',
 'Un equipo de fútbol recupera el primer puesto de la liga',
 'El calor récord reduce las posibilidades de recuperación de los bosques',
 'Científicos descubren un aumento de la mortalidad de animales marinos',
]
p=Path(__file__).resolve().parents[1]/'data/training/editorial_seed.jsonl'
with p.open('w',encoding='utf8') as f:
 for label,rows in [('constructive',positive),('not_constructive',negative)]:
  for title in rows: f.write(json.dumps({'title':title,'deck':'','label':label,'origin':'synthetic_bootstrap'},ensure_ascii=False)+'\n')
print('wrote',len(positive),len(negative))
