// GUD must discover positive stories across the normal web.
// Dedicated "good news" / "positive news" publishers are intentionally excluded.
export const blockedPublisherDomains = [
    'goodnewsnetwork.org',
    'positive.news',
    'goodgoodgood.co',
    'optimistdaily.com',
    'sunnyskyz.com',
    'reasonstobecheerful.world',
    'goodnews.eu',
    'thehappynewspaper.com',
];
// The pool is intentionally much larger than the 24-story edition.
// A source can fail, publish nothing in the previous 24 hours, or simply have
// no story that passes GUD's editorial rules. The selector accepts at most one
// story per publisher domain.
export const newsSources = [
    // Primary / public-interest institutions
    {
        id: 'nasa',
        name: 'NASA',
        url: 'https://www.nasa.gov/feed/',
        publisherDomain: 'nasa.gov',
        category: 'science',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'esa',
        name: 'European Space Agency',
        url: 'https://www.esa.int/rssfeed/Our_Activities/Space_News',
        publisherDomain: 'esa.int',
        category: 'science',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'nsf',
        name: 'National Science Foundation',
        url: 'https://www.nsf.gov/rss/rss_www_news.xml',
        publisherDomain: 'nsf.gov',
        category: 'science',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'who',
        name: 'World Health Organization',
        url: 'https://www.who.int/rss-feeds/news-english.xml',
        publisherDomain: 'who.int',
        category: 'health',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'nih',
        name: 'National Institutes of Health',
        url: 'https://www.nih.gov/nih-research-matters/feed.xml',
        publisherDomain: 'nih.gov',
        category: 'health',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'cdc',
        name: 'CDC',
        url: 'https://www.cdc.gov/media/rss.xml',
        publisherDomain: 'cdc.gov',
        category: 'health',
        kind: 'primary',
        priority: 2,
    },
    {
        id: 'noaa',
        name: 'NOAA',
        url: 'https://www.noaa.gov/news-features/feed',
        publisherDomain: 'noaa.gov',
        category: 'planet',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'nrel',
        name: 'National Renewable Energy Laboratory',
        url: 'https://www.nrel.gov/news/rss.xml',
        publisherDomain: 'nrel.gov',
        category: 'technology',
        kind: 'primary',
        priority: 3,
    },
    {
        id: 'doe',
        name: 'U.S. Department of Energy',
        url: 'https://www.energy.gov/rss.xml',
        publisherDomain: 'energy.gov',
        category: 'technology',
        kind: 'primary',
        priority: 2,
    },
    {
        id: 'un-news',
        name: 'UN News',
        url: 'https://news.un.org/feed/subscribe/en/news/all/rss.xml',
        publisherDomain: 'news.un.org',
        category: 'world',
        kind: 'primary',
        priority: 2,
    },
    {
        id: 'smithsonian-insider',
        name: 'Smithsonian Insider',
        url: 'https://insider.si.edu/feed/',
        publisherDomain: 'si.edu',
        category: 'science',
        kind: 'primary',
        priority: 2,
    },
    // Universities / research institutions
    {
        id: 'mit',
        name: 'MIT News',
        url: 'https://news.mit.edu/rss/feed',
        publisherDomain: 'mit.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'harvard',
        name: 'Harvard Gazette',
        url: 'https://news.harvard.edu/gazette/feed',
        publisherDomain: 'harvard.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'yale',
        name: 'Yale News',
        url: 'https://news.yale.edu/news-rss',
        publisherDomain: 'yale.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'berkeley',
        name: 'Berkeley News',
        url: 'https://news.berkeley.edu/feed/',
        publisherDomain: 'berkeley.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'cornell',
        name: 'Cornell Chronicle',
        url: 'https://news.cornell.edu/taxonomy/term/15621/feed',
        publisherDomain: 'cornell.edu',
        category: 'planet',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'duke',
        name: 'Duke Today',
        url: 'https://today.duke.edu/topics/environment-%26-sustainability/rss',
        publisherDomain: 'duke.edu',
        category: 'planet',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'cambridge',
        name: 'University of Cambridge',
        url: 'https://www.cam.ac.uk/news/feed',
        publisherDomain: 'cam.ac.uk',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'eth',
        name: 'ETH Zurich',
        url: 'https://www.ethz.ch/en/news-und-veranstaltungen/eth-news/news/_jcr_content.feed.html',
        publisherDomain: 'ethz.ch',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'johns-hopkins',
        name: 'Johns Hopkins Hub',
        url: 'https://hub.jhu.edu/feed/',
        publisherDomain: 'jhu.edu',
        category: 'health',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'stanford',
        name: 'Stanford Report',
        url: 'https://news.stanford.edu/feed/',
        publisherDomain: 'stanford.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'oxford',
        name: 'University of Oxford',
        url: 'https://www.ox.ac.uk/feeds/news.xml',
        publisherDomain: 'ox.ac.uk',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'imperial',
        name: 'Imperial College London',
        url: 'https://www.imperial.ac.uk/news/rss/',
        publisherDomain: 'imperial.ac.uk',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'princeton',
        name: 'Princeton University',
        url: 'https://www.princeton.edu/news/feed',
        publisherDomain: 'princeton.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'caltech',
        name: 'Caltech',
        url: 'https://www.caltech.edu/about/news/rss.xml',
        publisherDomain: 'caltech.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'uchicago',
        name: 'University of Chicago News',
        url: 'https://news.uchicago.edu/rss.xml',
        publisherDomain: 'uchicago.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'ucl',
        name: 'UCL News',
        url: 'https://www.ucl.ac.uk/news/rss.xml',
        publisherDomain: 'ucl.ac.uk',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'uw',
        name: 'University of Washington',
        url: 'https://www.washington.edu/news/feed/',
        publisherDomain: 'washington.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'michigan',
        name: 'University of Michigan Record',
        url: 'https://record.umich.edu/feed/',
        publisherDomain: 'umich.edu',
        category: 'people',
        kind: 'institution',
        priority: 1,
    },
    {
        id: 'rice',
        name: 'Rice University News',
        url: 'https://news.rice.edu/news/feed',
        publisherDomain: 'rice.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'brown',
        name: 'Brown University News',
        url: 'https://www.brown.edu/news/feed',
        publisherDomain: 'brown.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'northwestern',
        name: 'Northwestern Now',
        url: 'https://news.northwestern.edu/rss.xml',
        publisherDomain: 'northwestern.edu',
        category: 'science',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'penn-state',
        name: 'Penn State News',
        url: 'https://www.psu.edu/news/rss',
        publisherDomain: 'psu.edu',
        category: 'science',
        kind: 'institution',
        priority: 1,
    },
    // Science / health / technology journalism
    {
        id: 'smithsonian',
        name: 'Smithsonian Magazine',
        url: 'https://www.smithsonianmag.com/rss/science-nature/',
        publisherDomain: 'smithsonianmag.com',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'ars-science',
        name: 'Ars Technica',
        url: 'https://feeds.arstechnica.com/arstechnica/science',
        publisherDomain: 'arstechnica.com',
        category: 'technology',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'phys-org',
        name: 'Phys.org',
        url: 'https://phys.org/rss-feed/',
        publisherDomain: 'phys.org',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'medical-xpress',
        name: 'Medical Xpress',
        url: 'https://medicalxpress.com/rss-feed/',
        publisherDomain: 'medicalxpress.com',
        category: 'health',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'science-daily',
        name: 'ScienceDaily',
        url: 'https://www.sciencedaily.com/rss/top/science.xml',
        publisherDomain: 'sciencedaily.com',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'quanta',
        name: 'Quanta Magazine',
        url: 'https://www.quantamagazine.org/feed/',
        publisherDomain: 'quantamagazine.org',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'nautilus',
        name: 'Nautilus',
        url: 'https://nautil.us/feed/',
        publisherDomain: 'nautil.us',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'undark',
        name: 'Undark',
        url: 'https://undark.org/feed/',
        publisherDomain: 'undark.org',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'science-alert',
        name: 'ScienceAlert',
        url: 'https://www.sciencealert.com/feed',
        publisherDomain: 'sciencealert.com',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'aeon',
        name: 'Aeon',
        url: 'https://aeon.co/feed.rss',
        publisherDomain: 'aeon.co',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'new-atlas',
        name: 'New Atlas',
        url: 'https://newatlas.com/index.rss',
        publisherDomain: 'newatlas.com',
        category: 'technology',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'tech-xplore',
        name: 'Tech Xplore',
        url: 'https://techxplore.com/rss-feed/',
        publisherDomain: 'techxplore.com',
        category: 'technology',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'ieee-spectrum',
        name: 'IEEE Spectrum',
        url: 'https://spectrum.ieee.org/feeds/feed.rss',
        publisherDomain: 'spectrum.ieee.org',
        category: 'technology',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'scientific-american',
        name: 'Scientific American',
        url: 'https://www.scientificamerican.com/feed/',
        publisherDomain: 'scientificamerican.com',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'live-science',
        name: 'Live Science',
        url: 'https://www.livescience.com/feeds/all',
        publisherDomain: 'livescience.com',
        category: 'science',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'popular-science',
        name: 'Popular Science',
        url: 'https://www.popsci.com/feed/',
        publisherDomain: 'popsci.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'futurity',
        name: 'Futurity',
        url: 'https://www.futurity.org/feed/',
        publisherDomain: 'futurity.org',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'research-matters-india',
        name: 'Research Matters',
        url: 'https://researchmatters.in/rss.xml',
        publisherDomain: 'researchmatters.in',
        category: 'science',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'the-verge',
        name: 'The Verge',
        url: 'https://www.theverge.com/rss/index.xml',
        publisherDomain: 'theverge.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'wired',
        name: 'WIRED',
        url: 'https://www.wired.com/feed/rss',
        publisherDomain: 'wired.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'techcrunch',
        name: 'TechCrunch',
        url: 'https://techcrunch.com/feed/',
        publisherDomain: 'techcrunch.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'fast-company',
        name: 'Fast Company',
        url: 'https://www.fastcompany.com/rss',
        publisherDomain: 'fastcompany.com',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    // Environment / climate / conservation
    {
        id: 'mongabay',
        name: 'Mongabay',
        url: 'https://news.mongabay.com/feed/',
        publisherDomain: 'mongabay.com',
        category: 'planet',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'inside-climate-news',
        name: 'Inside Climate News',
        url: 'https://insideclimatenews.org/feed/',
        publisherDomain: 'insideclimatenews.org',
        category: 'planet',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'yale-e360',
        name: 'Yale Environment 360',
        url: 'https://e360.yale.edu/feed.xml',
        publisherDomain: 'e360.yale.edu',
        category: 'planet',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'carbon-brief',
        name: 'Carbon Brief',
        url: 'https://carbonbrief.org/feed/',
        publisherDomain: 'carbonbrief.org',
        category: 'planet',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'grist',
        name: 'Grist',
        url: 'https://grist.org/feed/',
        publisherDomain: 'grist.org',
        category: 'planet',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'cleantechnica',
        name: 'CleanTechnica',
        url: 'https://cleantechnica.com/feed/',
        publisherDomain: 'cleantechnica.com',
        category: 'planet',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'electrek',
        name: 'Electrek',
        url: 'https://electrek.co/feed/',
        publisherDomain: 'electrek.co',
        category: 'technology',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'canary-media',
        name: 'Canary Media',
        url: 'https://www.canarymedia.com/rss.rss',
        publisherDomain: 'canarymedia.com',
        category: 'planet',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'hakaimagazine',
        name: 'Hakai Magazine',
        url: 'https://hakaimagazine.com/feed/',
        publisherDomain: 'hakaimagazine.com',
        category: 'planet',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'earth-org',
        name: 'Earth.Org',
        url: 'https://earth.org/feed/',
        publisherDomain: 'earth.org',
        category: 'planet',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'birdlife',
        name: 'BirdLife International',
        url: 'https://www.birdlife.org/feed/',
        publisherDomain: 'birdlife.org',
        category: 'animals',
        kind: 'institution',
        priority: 2,
    },
    {
        id: 'audubon',
        name: 'Audubon',
        url: 'https://www.audubon.org/rss.xml',
        publisherDomain: 'audubon.org',
        category: 'animals',
        kind: 'institution',
        priority: 1,
    },
    {
        id: 'wildlife-society',
        name: 'The Wildlife Society',
        url: 'https://wildlife.org/feed/',
        publisherDomain: 'wildlife.org',
        category: 'animals',
        kind: 'institution',
        priority: 1,
    },
    {
        id: 'ocean-conservancy',
        name: 'Ocean Conservancy',
        url: 'https://oceanconservancy.org/feed/',
        publisherDomain: 'oceanconservancy.org',
        category: 'planet',
        kind: 'institution',
        priority: 1,
    },
    {
        id: 'wwf',
        name: 'World Wildlife Fund',
        url: 'https://www.worldwildlife.org/stories.rss',
        publisherDomain: 'worldwildlife.org',
        category: 'animals',
        kind: 'institution',
        priority: 2,
    },
    // Culture / design / architecture / archaeology
    {
        id: 'hyperallergic',
        name: 'Hyperallergic',
        url: 'https://hyperallergic.com/feed/',
        publisherDomain: 'hyperallergic.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'dezeen',
        name: 'Dezeen',
        url: 'https://www.dezeen.com/feed/',
        publisherDomain: 'dezeen.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'designboom',
        name: 'Designboom',
        url: 'https://www.designboom.com/feed/',
        publisherDomain: 'designboom.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'colossal',
        name: 'Colossal',
        url: 'https://www.thisiscolossal.com/feed/',
        publisherDomain: 'thisiscolossal.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'creative-boom',
        name: 'Creative Boom',
        url: 'https://www.creativeboom.com/feed/',
        publisherDomain: 'creativeboom.com',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'core77',
        name: 'Core77',
        url: 'https://www.core77.com/rss',
        publisherDomain: 'core77.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'design-milk',
        name: 'Design Milk',
        url: 'https://design-milk.com/feed/',
        publisherDomain: 'design-milk.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'archdaily',
        name: 'ArchDaily',
        url: 'https://www.archdaily.com/feed',
        publisherDomain: 'archdaily.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'archaeology',
        name: 'Archaeology Magazine',
        url: 'https://archaeology.org/feed/',
        publisherDomain: 'archaeology.org',
        category: 'culture',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'atlas-obscura',
        name: 'Atlas Obscura',
        url: 'https://www.atlasobscura.com/feeds/latest',
        publisherDomain: 'atlasobscura.com',
        category: 'culture',
        kind: 'journalism',
        priority: 0,
    },
    // Society / education / mobility
    {
        id: 'edsurge',
        name: 'EdSurge',
        url: 'https://www.edsurge.com/articles_rss',
        publisherDomain: 'edsurge.com',
        category: 'people',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'streetsblog',
        name: 'Streetsblog USA',
        url: 'https://usa.streetsblog.org/feed',
        publisherDomain: 'streetsblog.org',
        category: 'people',
        kind: 'journalism',
        priority: 1,
    },
    {
        id: 'nonprofit-quarterly',
        name: 'Nonprofit Quarterly',
        url: 'https://nonprofitquarterly.org/feed/',
        publisherDomain: 'nonprofitquarterly.org',
        category: 'people',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'the-conversation',
        name: 'The Conversation',
        url: 'https://theconversation.com/us/articles.atom',
        publisherDomain: 'theconversation.com',
        category: 'world',
        kind: 'journalism',
        priority: 0,
    },
    // Large general outlets / global discovery
    {
        id: 'bbc-science',
        name: 'BBC News',
        url: 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml',
        publisherDomain: 'bbc.co.uk',
        category: 'science',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'guardian-science',
        name: 'The Guardian',
        url: 'https://www.theguardian.com/science/rss',
        publisherDomain: 'theguardian.com',
        category: 'science',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'npr-science',
        name: 'NPR',
        url: 'https://feeds.npr.org/1007/rss.xml',
        publisherDomain: 'npr.org',
        category: 'science',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'dw',
        name: 'DW',
        url: 'https://rss.dw.com/xml/rss-en-all',
        publisherDomain: 'dw.com',
        category: 'world',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'france24',
        name: 'France 24',
        url: 'https://www.france24.com/en/rss',
        publisherDomain: 'france24.com',
        category: 'world',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'al-jazeera',
        name: 'Al Jazeera',
        url: 'https://www.aljazeera.com/xml/rss/all.xml',
        publisherDomain: 'aljazeera.com',
        category: 'world',
        kind: 'journalism',
        priority: 0,
    },
    {
        id: 'cbc',
        name: 'CBC News',
        url: 'https://www.cbc.ca/cmlink/rss-topstories',
        publisherDomain: 'cbc.ca',
        category: 'world',
        kind: 'journalism',
        priority: 0,
    },
];
